http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

cbs:
    imagesPath:
      file:/D:/img/
server:
  port: 8888
  tomcat:
    uri-encoding: UTF-8
#  servlet:
#    jsp:
#      init-parameters:
#        development = true
spring:
  resources:
    static-locations: classpath:/static/
  devtools:
    restart:
      additional-paths: resources/**,static/**,templates/**
      enabled: true
  thymeleaf:
#    prefix: classpath:/templates
#    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    servlet:
#      content-type: text/html
    cache: false
  application:
    name: article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: edwards
    type: com.alibaba.druid.pool.DruidDataSource

    initialSize: 50

    maxActive: 200

    maxWait: 60000

    minIdle: 20

    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000

    validationQuery: SELECT 1 FROM DUAL

    testWhileIdle: true

    testOnBorrow: false

    testOnReturn: false

    poolPreparedStatements: true

    filters: stat,wall,log4j

    maxPoolPreparedStatementPerConnectionSize: 20

    useGlobalDataSourceStat: true

    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp/
#      suffix: .jsp
mybatis:
  mapper-locations: classpath:mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true
